<a href="https://colab.research.google.com/github/DomiMM/DomiMM/blob/main/P4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df_x = pd.read_csv("bioactivity_clean_and_processed_data_pIC50.csv")

In [ ]:
import pandas as pd
df_y = pd.read_csv("descriptors_output (3).csv")

In [ ]:
df_x

,Unnamed: 0,molecule_chembl_id,canonical_smiles,0,pIC50
0,0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,6.124939
1,1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,7.000000
2,2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,4.301030
3,3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,6.522879
4,4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,6.096910
...,...,...,...,...,...
5751,5751,CHEMBL4291400,CCN1CCN(C2CCN(C(=O)COc3ccc(I)cc3)CC2)CC1,active,4.698970
5752,5752,CHEMBL4280753,CCN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,active,4.060481
5753,5753,CHEMBL4281203,CN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,inactive,3.860121
5754,5754,CHEMBL4289086,O=C(COc1ccc(I)cc1)NCCCN1CCCCC1,active,4.886057
5755,5755,CHEMBL4284619,CCN1CCN(C2CCN(C(=O)COc3ccc(-c4ccc(OC)cc4)cc3)C...,active,4.744727

In [ ]:
df_y

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL336398,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL133897,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL130628,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL131588,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL130478,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5659,CHEMBL4779440,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5660,CHEMBL417799,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5661,CHEMBL13045,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5662,CHEMBL253998,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5663,CHEMBL3085398,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_final = pd.concat([df_y, df_x], axis=1)

In [ ]:
df_final

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,Unnamed: 0,molecule_chembl_id,canonical_smiles,0,pIC50
0,CHEMBL336398,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,6.124939
1,CHEMBL133897,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,7.000000
2,CHEMBL130628,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,4.301030
3,CHEMBL131588,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,6.522879
4,CHEMBL130478,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5751,CHEMBL4291400,CCN1CCN(C2CCN(C(=O)COc3ccc(I)cc3)CC2)CC1,active,4.698970
5752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5752,CHEMBL4280753,CCN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,active,4.060481
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5753,CHEMBL4281203,CN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,inactive,3.860121
5754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5754,CHEMBL4289086,O=C(COc1ccc(I)cc1)NCCCN1CCCCC1,active,4.886057
5755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5755,CHEMBL4284619,CCN1CCN(C2CCN(C(=O)COc3ccc(-c4ccc(OC)cc4)cc3)C...,active,4.744727

In [ ]:
df_final_1= df_final.drop("molecule_chembl_id", axis=1)

In [ ]:
df_final_1

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,Unnamed: 0,canonical_smiles,0,pIC50
0,CHEMBL336398,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,6.124939
1,CHEMBL133897,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,7.000000
2,CHEMBL130628,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,4.301030
3,CHEMBL131588,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,6.522879
4,CHEMBL130478,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5751,CCN1CCN(C2CCN(C(=O)COc3ccc(I)cc3)CC2)CC1,active,4.698970
5752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5752,CCN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,active,4.060481
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5753,CN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,inactive,3.860121
5754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5754,O=C(COc1ccc(I)cc1)NCCCN1CCCCC1,active,4.886057
5755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5755,CCN1CCN(C2CCN(C(=O)COc3ccc(-c4ccc(OC)cc4)cc3)C...,active,4.744727

In [ ]:
df_final_2= df_final.drop("Unnamed: 0", axis=1)

In [ ]:
df_final_2

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,molecule_chembl_id,canonical_smiles,0,pIC50
0,CHEMBL336398,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,6.124939
1,CHEMBL133897,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,7.000000
2,CHEMBL130628,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,4.301030
3,CHEMBL131588,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,6.522879
4,CHEMBL130478,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CHEMBL4291400,CCN1CCN(C2CCN(C(=O)COc3ccc(I)cc3)CC2)CC1,active,4.698970
5752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CHEMBL4280753,CCN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,active,4.060481
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CHEMBL4281203,CN1CCN(CCCNC(=O)COc2ccc(I)cc2)CC1,inactive,3.860121
5754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CHEMBL4289086,O=C(COc1ccc(I)cc1)NCCCN1CCCCC1,active,4.886057
5755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CHEMBL4284619,CCN1CCN(C2CCN(C(=O)COc3ccc(-c4ccc(OC)cc4)cc3)C...,active,4.744727

In [ ]:
df_final_1.to_csv("final_data_paddel_descritpors_bioactivity_data.csv")