<a href="https://colab.research.google.com/github/DomiMM/DomiMM/blob/main/training_data_to_pkl_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.0.10)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [6]:
df = pd.read_excel("master_1.1.xlsx", engine='openpyxl')

In [7]:
df.head()

,idx,target,protocol,src_ip,src_port,dst_ip,dst_port,packet_length,tcp_flags,window_size,...,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time
0,1,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,1.689704e+09
1,2,galaxy_s10,UDP,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
2,39,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,4.847050e-03
3,44,galaxy_s10,UDP,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
4,45,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ackfin,NaN,...,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,8.093119e-03

In [8]:
df = df.reset_index(drop=True)

In [9]:
df.at[0, 'idx'] = 2

In [10]:
df.head()

,idx,target,protocol,src_ip,src_port,dst_ip,dst_port,packet_length,tcp_flags,window_size,...,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time
0,2,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,1.689704e+09
1,2,galaxy_s10,UDP,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
2,39,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,4.847050e-03
3,44,galaxy_s10,UDP,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
4,45,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ackfin,NaN,...,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,8.093119e-03

In [11]:
df.head()

,idx,target,protocol,src_ip,src_port,dst_ip,dst_port,packet_length,tcp_flags,window_size,...,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time
0,2,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,1.689704e+09
1,2,galaxy_s10,UDP,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
2,39,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,...,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,4.847050e-03
3,44,galaxy_s10,UDP,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,NaN,NaN,...,NaN,NaN,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09
4,45,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ackfin,NaN,...,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,8.093119e-03

In [12]:
df = df.drop(columns=['idx'])

In [13]:
#df = df.drop(columns=['1'])

In [14]:
#df = df.drop(df.columns[0], axis=1)

In [15]:
df.head(15)

,target,protocol,src_ip,src_port,dst_ip,dst_port,packet_length,tcp_flags,window_size,ttl,...,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time
0,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,64,...,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.012940,321,24806.477826,1.689704e+09
1,galaxy_s10,UDP,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,NaN,NaN,64,...,NaN,NaN,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.000000,87,0.000000,1.689704e+09
2,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ack,NaN,64,...,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.012940,321,24806.477826,4.847050e-03
3,galaxy_s10,UDP,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,NaN,NaN,64,...,NaN,NaN,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.000000,87,0.000000,1.689704e+09
4,galaxy_s10,TCP,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,ackfin,NaN,64,...,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.012940,321,24806.477826,8.093119e-03
5,galaxy_s10,TCP,192.168.1.126,41952.0,172.217.168.42,443.0,105.0,ack,356.0,64,...,NaN,NaN,192.168.1.126:41952-172.217.168.42:443-TCP,9,1.689704e+09,1.689704e+09,0.017873,261,14602.992650,1.689704e+09
6,galaxy_s10,UDP,192.168.1.126,14013.0,192.168.1.1,53.0,94.0,NaN,NaN,64,...,NaN,NaN,192.168.1.126:14013-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.000000,94,0.000000,1.689704e+09
7,galaxy_s10,TCP,192.168.1.126,41952.0,172.217.168.42,443.0,90.0,ack,356.0,64,...,NaN,NaN,192.168.1.126:41952-172.217.168.42:443-TCP,9,1.689704e+09,1.689704e+09,0.017873,261,14602.992650,6.557941e-03
8,galaxy_s10,UDP,192.168.1.126,43647.0,192.168.1.1,53.0,94.0,NaN,NaN,64,...,NaN,NaN,192.168.1.126:43647-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.000000,94,0.000000,1.689704e+09
9,galaxy_s10,TCP,192.168.1.126,41952.0,172.217.168.42,443.0,66.0,ackfin,356.0,64,...,NaN,NaN,192.168.1.126:41952-172.217.168.42:443-TCP,9,1.689704e+09,1.689704e+09,0.017873,261,14602.992650,1.131511e-02
10,galaxy_s10,NaN,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,NaN,fe80::1e24:cdff:fe93:ae00,NaN,NaN,NaN,NaN,255,...,58.0,32.0,NaN,0,0.000000e+00,0.000000e+00,0.000000,0,0.000000,1.689704e+09
11,galaxy_s10,TCP,192.168.1.126,33941.0,138.188.127.131,5061.0,87.0,ack,377.0,64,...,NaN,NaN,192.168.1.126:33941-138.188.127.131:5061-TCP,6,1.689704e+09,1.689704e+09,0.007982,147,18416.400968,1.689704e+09
12,galaxy_s10,TCP,192.168.1.126,33941.0,138.188.127.131,5061.0,60.0,ack,377.0,64,...,NaN,NaN,192.168.1.126:33941-138.188.127.131:5061-TCP,6,1.689704e+09,1.689704e+09,0.007982,147,18416.400968,7.982016e-03
13,galaxy_s10,TCP,192.168.1.126,50712.0,108.177.126.188,5228.0,66.0,ack,463.0,64,...,NaN,NaN,192.168.1.126:50712-108.177.126.188:5228-TCP,6,1.689704e+09,1.689704e+09,0.055179,170,3080.888881,1.689704e+09
14,galaxy_s10,TCP,192.168.1.126,50712.0,108.177.126.188,5228.0,104.0,ack,463.0,64,...,NaN,NaN,192.168.1.126:50712-108.177.126.188:5228-TCP,6,1.689704e+09,1.689704e+09,0.055179,170,3080.888881,5.517888e-02

In [16]:
df.dropna()

Empty DataFrame
Columns: [target, protocol, src_ip, src_port, dst_ip, dst_port, packet_length, tcp_flags, window_size, ttl, frame_len, dsfield_dscp, app_layer_protocol, dsfield_ecn, flags_df, flags_mf, ip_hdr_len, ip_id, ip_len, udp_src_port, udp_dst_port, udp_length, udp_checksum_status, packet_eth_src, flow_label, traffic_class, next_header, payload_len, Flow, Packet_Count, Start_Time, End_Time, Duration, Flow_Volume, Flow_Rate, Inter_Arrival_Time]
Index: []

[0 rows x 36 columns]

In [17]:
df = pd.get_dummies(df, columns=['app_layer_protocol'])

In [18]:
df = pd.get_dummies(df, columns=['protocol'])

In [19]:
#df = pd.get_dummies(df, columns=['ip_id'])

In [20]:
df['ip_id'] = df['ip_id'].apply(lambda x: int(x, 16) if isinstance(x, str) else x)

In [21]:
df = pd.get_dummies(df, columns=['tcp_flags'])

In [22]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)  # Show all rows

In [23]:
df.head()

,target,src_ip,src_port,dst_ip,dst_port,packet_length,window_size,ttl,frame_len,dsfield_dscp,dsfield_ecn,flags_df,flags_mf,ip_hdr_len,ip_id,ip_len,udp_src_port,udp_dst_port,udp_length,udp_checksum_status,packet_eth_src,flow_label,traffic_class,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time,app_layer_protocol_DNS,app_layer_protocol_HTTP,app_layer_protocol_TCP,app_layer_protocol_UDP,protocol_TCP,protocol_UDP,tcp_flags_ack,tcp_flags_ackfin,tcp_flags_syn
0,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,NaN,64,NaN,NaN,NaN,NaN,NaN,40,NaN,71,NaN,NaN,NaN,NaN,NaN,0x0a60ca,0x00000000,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,1.689704e+09,0,0,0,0,1,0,1,0,0
1,galaxy_s10,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,NaN,64,87.0,0.0,0.0,1.0,0.0,20,2111.0,73,48180.0,53.0,53.0,2.0,f6:e6:56:8b:50:ee,NaN,NaN,NaN,NaN,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09,1,0,0,0,0,1,0,0,0
2,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,NaN,64,NaN,NaN,NaN,NaN,NaN,40,NaN,56,NaN,NaN,NaN,NaN,NaN,0x0a60ca,0x00000000,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,4.847050e-03,0,0,0,0,1,0,1,0,0
3,galaxy_s10,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,NaN,64,87.0,0.0,0.0,1.0,0.0,20,2113.0,73,42999.0,53.0,53.0,2.0,f6:e6:56:8b:50:ee,NaN,NaN,NaN,NaN,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09,1,0,0,0,0,1,0,0,0
4,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,NaN,NaN,64,NaN,NaN,NaN,NaN,NaN,40,NaN,32,NaN,NaN,NaN,NaN,NaN,0x0a60ca,0x00000000,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,8.093119e-03,0,0,0,0,1,0,0,1,0

In [24]:
df = df.fillna(0)

In [25]:
#X = df.drop(columns=["src_ip", "src_hostname", "dst_ip", "dst_hostname", "tcp_flags", "target", "packet_number_idx", "src_port", "Mean Backward Interarrival Time", "Mean Forward Interarrival Time", "0-200", "201-400", "401-600", "601-800", "801-1000", "1001-1200", "1201-1500", "packet.eth.src", "Flow", "IP", "Packet_Count", "udp_src_port", "ip_id", "dst_port", "udp_dst_port"])

In [26]:
#X = df.drop(columns=["src_ip", "src_hostname", "dst_ip", "dst_hostname", "tcp_flags", "target", "packet_number_idx", "src_port", "packet.eth.src", "Flow", "IP", "udp_src_port", "ip_id", "dst_port", "udp_dst_port", "Start_Time", "nd_Time"])

In [27]:
df.head()

,target,src_ip,src_port,dst_ip,dst_port,packet_length,window_size,ttl,frame_len,dsfield_dscp,dsfield_ecn,flags_df,flags_mf,ip_hdr_len,ip_id,ip_len,udp_src_port,udp_dst_port,udp_length,udp_checksum_status,packet_eth_src,flow_label,traffic_class,next_header,payload_len,Flow,Packet_Count,Start_Time,End_Time,Duration,Flow_Volume,Flow_Rate,Inter_Arrival_Time,app_layer_protocol_DNS,app_layer_protocol_HTTP,app_layer_protocol_TCP,app_layer_protocol_UDP,protocol_TCP,protocol_UDP,tcp_flags_ack,tcp_flags_ackfin,tcp_flags_syn
0,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,0.0,0.0,64,0.0,0.0,0.0,0.0,0.0,40,0.0,71,0.0,0.0,0.0,0.0,0,0x0a60ca,0x00000000,6.0,71.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,1.689704e+09,0,0,0,0,1,0,1,0,0
1,galaxy_s10,192.168.1.126,48180.0,192.168.1.1,53.0,87.0,0.0,64,87.0,0.0,0.0,1.0,0.0,20,2111.0,73,48180.0,53.0,53.0,2.0,f6:e6:56:8b:50:ee,0,0,0.0,0.0,192.168.1.126:48180-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09,1,0,0,0,0,1,0,0,0
2,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,0.0,0.0,64,0.0,0.0,0.0,0.0,0.0,40,0.0,56,0.0,0.0,0.0,0.0,0,0x0a60ca,0x00000000,6.0,56.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,4.847050e-03,0,0,0,0,1,0,1,0,0
3,galaxy_s10,192.168.1.126,42999.0,192.168.1.1,53.0,87.0,0.0,64,87.0,0.0,0.0,1.0,0.0,20,2113.0,73,42999.0,53.0,53.0,2.0,f6:e6:56:8b:50:ee,0,0,0.0,0.0,192.168.1.126:42999-192.168.1.1:53-UDP,3,1.689704e+09,1.689704e+09,0.00000,87,0.000000,1.689704e+09,1,0,0,0,0,1,0,0,0
4,galaxy_s10,2a02:1210:3a86:7900:5d4b:f033:6de2:3508,42312.0,2a00:1450:400a:800::200a,443.0,0.0,0.0,64,0.0,0.0,0.0,0.0,0.0,40,0.0,32,0.0,0.0,0.0,0.0,0,0x0a60ca,0x00000000,6.0,32.0,2a02:1210:3a86:7900:5d4b:f033:6de2:3508:42312-...,9,1.689704e+09,1.689704e+09,0.01294,321,24806.477826,8.093119e-03,0,0,0,0,1,0,0,1,0

In [28]:
X = df.drop(columns=[
    'target', 'src_ip', 'src_port', 'dst_ip', 'dst_port', 'packet_eth_src', 'flow_label',
    'traffic_class', 'Flow', 'Start_Time', 'End_Time', 'Duration', 'ip_len', 'payload_len',
    'tcp_flags_ack', 'protocol_UDP', 'tcp_flags_ackfin', 'protocol_TCP', 'next_header',
    'tcp_flags_syn', 'udp_src_port', 'dsfield_ecn', 'dsfield_dscp', 'flags_mf', 'udp_checksum_status', 'udp_dst_port', 'udp_length','flags_df', 'frame_len', 'ip_hdr_len'
])

In [29]:
X.head()

,packet_length,window_size,ttl,ip_id,Packet_Count,Flow_Volume,Flow_Rate,Inter_Arrival_Time,app_layer_protocol_DNS,app_layer_protocol_HTTP,app_layer_protocol_TCP,app_layer_protocol_UDP
0,0.0,0.0,64,0.0,9,321,24806.477826,1.689704e+09,0,0,0,0
1,87.0,0.0,64,2111.0,3,87,0.000000,1.689704e+09,1,0,0,0
2,0.0,0.0,64,0.0,9,321,24806.477826,4.847050e-03,0,0,0,0
3,87.0,0.0,64,2113.0,3,87,0.000000,1.689704e+09,1,0,0,0
4,0.0,0.0,64,0.0,9,321,24806.477826,8.093119e-03,0,0,0,0

In [30]:
Y = df.target

In [31]:
X = X.astype(float)

In [32]:
X.columns = X.columns.astype(str)

In [33]:
Y = Y.astype(str)

In [34]:
X.to_csv('X.csv', index=False)

In [35]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [36]:
# Convert your DataFrames to numpy arrays if they are not already
X = X.values if isinstance(X, pd.DataFrame) else X
Y = Y.values if isinstance(Y, pd.DataFrame) else Y

In [37]:
# Define the KFold cross-validator (5 folds in your case)
kf = KFold(n_splits=5, random_state=1, shuffle=True)

In [38]:
scores = []

In [39]:
for i, (train_index, val_index) in enumerate(kf.split(X)):
    X_train, X_val = X[train_index], X[val_index]
    Y_train, Y_val = Y[train_index], Y[val_index]

    # Train the classifier
    clf = RandomForestClassifier(n_estimators=100)
    clf.fit(X_train, Y_train)

    # Predict on the validation set and calculate the accuracy
    Y_pred = clf.predict(X_val)
    accuracy = accuracy_score(Y_val, Y_pred)
    scores.append(accuracy)

    # If it's the first fold (0-based index), print some data for inspection
    if i == 0:
        print(f'Data in fold {i+1}')
        print('First 5 samples of training set:')
        print(X_train[:5])  # printing only the first 5 samples
        print('First 5 samples of validation set:')
        print(X_val[:5])  # printing only the first 5 samples

Data in fold 1
First 5 samples of training set:
[[0.00000000e+00 0.00000000e+00 6.40000000e+01 0.00000000e+00
  9.00000000e+00 3.21000000e+02 2.48064778e+04 1.68970429e+09
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.70000000e+01 0.00000000e+00 6.40000000e+01 2.11100000e+03
  3.00000000e+00 8.70000000e+01 0.00000000e+00 1.68970429e+09
  1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.40000000e+01 0.00000000e+00
  9.00000000e+00 3.21000000e+02 2.48064778e+04 4.84704971e-03
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.70000000e+01 0.00000000e+00 6.40000000e+01 2.11300000e+03
  3.00000000e+00 8.70000000e+01 0.00000000e+00 1.68970429e+09
  1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.40000000e+01 0.00000000e+00
  9.00000000e+00 3.21000000e+02 2.48064778e+04 8.09311867e-03
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
First 5 samples of validation set:
[[6.60000000e+01 1.28500000e+03 6.40000000e+01 4.91750000e+04
  4.32000000e+02 9.50400000e+03 3.08588970e+03 1.17919445e-02
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.60000000e+01 5.31000000e+02 6.40000000e+01 4.91820000e+04
  4.32000000e+02 9.50400000e+03 3.08588970e+03 1.02088451e-02
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.60000000e+01 5.20000000e+01 6.40000000e+01 4.91870000e+04
  4.32000000e+02 9.50400000e+03 3.08588970e+03 1.91388130e-02
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.60000000e+01 0.00000000e+00 6.40000000e+01 4.91880000e+04
  4.32000000e+02 9.50400000e+03 3.08588970e+03 9.57298279e-03
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.60000000e+01 3.00000000e+00 6.40000000e+01 4.91930000e+04
  4.32000000e+02 9.50400000e+03 3.08588970e+03 4.42700386e-02
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]]

In [40]:
# Print the accuracy results
for i, score in enumerate(scores, start=1):
    print(f"Accuracy for fold {i}: {score}")
print("Average accuracy: ", np.mean(scores))
print("Standard deviation: ", np.std(scores))

Accuracy for fold 1: 0.9886591060707138
Accuracy for fold 2: 0.9873248832555037
Accuracy for fold 3: 0.9906604402935291
Accuracy for fold 4: 0.9866577718478986
Accuracy for fold 5: 0.9919946631087392
Average accuracy:  0.9890593729152769
Standard deviation:  0.0020057767015841154

In [46]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [47]:
# Placeholder lists to store metrics values for each fold
precisions = []
recalls = []
f1_scores = []

In [49]:
for i, (train_index, val_index) in enumerate(kf.split(X)):
    X_train, X_val = X[train_index], X[val_index]
    Y_train, Y_val = Y[train_index], Y[val_index]

    # Train the classifier
    clf = RandomForestClassifier(n_estimators=100)
    clf.fit(X_train, Y_train)

    # Predict on the validation set
    Y_pred = clf.predict(X_val)

    # Calculate the precision, recall, F1 score
    # Assuming you want 'macro' average. Change it as needed.
    precision = precision_score(Y_val, Y_pred, average='macro')
    recall = recall_score(Y_val, Y_pred, average='macro')
    f1 = f1_score(Y_val, Y_pred, average='macro')

    # Store the scores
    precisions.append(precision)
    recalls.append(recall)
    f1_scores.append(f1)

In [50]:
# Print the average metrics
print('Average precision:', np.mean(precisions))
print('Average recall:', np.mean(recalls))
print('Average F1 score:', np.mean(f1_scores))

Average precision: 0.9899274487532347
Average recall: 0.98998094671289
Average F1 score: 0.9899319431563894

In [42]:
# Store model
import pickle
pickle.dump(clf, open('iot_tool_2.pkl', 'wb'))

In [43]:
with open('reference_header.pkl', 'wb') as f:
    pickle.dump(df.columns.tolist(), f)

In [53]:
from sklearn.inspection import permutation_importance

# Assuming you have a trained random forest model named 'rf_model'
# and your input features and target labels are stored in 'X_test' and 'y_train' respectively

# Compute permutation importance
result = permutation_importance(clf, X_train, Y_train, n_repeats=10, random_state=42)

# Extract feature importance scores
feature_importance_scores = result.importances_mean

# Get the indices of features sorted by importance scores in descending order
sorted_idx = feature_importance_scores.argsort()[::-1]

# Print the feature importance scores and their corresponding feature names
for i in sorted_idx:
    print(f'Feature: {X_train.columns[i]}, Importance Score: {feature_importance_scores[i]}')

AttributeError: ignored